#!/bin/bash

available_options=()
for file in Dockerfile/attn/*-attn-builder.Dockerfile; do
  if [[ $file =~ ^Dockerfile/attn/ubuntu24_cuda([0-9.]+)-attn-builder.Dockerfile$ ]]; then
    available_options+=("--cuda-version ${BASH_REMATCH[1]}")
  fi
done

CUDA_VERSION=${2:-12.5.1}
PYTORCH_VERSION=${3:-}

if [[ ! " ${available_options[@]} " =~ " --cuda-version ${CUDA_VERSION} " ]]; then
  echo "Error: CUDA version ${CUDA_VERSION} is not available."
  exit 1
fi

if [ "$1" == "build" ]; then
  if [ -z "$(docker images -q | grep -E 'attn-builder')" ]; then
    docker build -f Dockerfile/attn/ubuntu24_cuda${CUDA_VERSION}-attn-builder.Dockerfile -t attn-builder .
  fi
  docker run --rm --gpus all -v ./builds:/builds -e PYTORCH_VERSION=${PYTORCH_VERSION} attn-builder
fi

if [ "$1" == "run" ]; then
  if ! docker images | grep -E '^comfyui-attn-runtime\s' 1>/dev/null; then
    docker build -f Dockerfile/ubuntu24_cuda${CUDA_VERSION}.Dockerfile -t comfyui-attn-runtime .
  fi

  cat ./attn.bash > /opt/comfyui/run/user_script.bash
  chmod +x /opt/comfyui/run/user_script.bash

  if ! chown -R $(id -u):$(id -g) /opt/comfyui; then
    echo "Please run the script with sudo to change ownership of /opt/comfyui"
  fi

  # Grants all permissions to myself and group, and read permission to other users on all files and directories within /opt/comfyui
  chmod -R ug+rwx,o+rw /opt/comfyui
  
  docker run --rm -it \
    --gpus all \
    -v /opt/comfyui/run:/comfy/mnt \
    -v /opt/comfyui/basedir:/basedir \
    -v /mnt/d/Images/:/mnt/d/Images/ \
    -v ./builds:/builds \
    -e WANTED_UID=$(id -u) \
    -e WANTED_GID=$(id -g) \
    -e BASE_DIRECTORY=/basedir \
    -e SECURITY_LEVEL=normal \
    -e COMFY_CMDLINE_EXTRA="--output-directory /mnt/d/Images/output --input-directory /mnt/d/Images/input" \
    -e PYTORCH_VERSION=${PYTORCH_VERSION} \
    -p 8188:8188 \
    --name comfyui-attn-runtime \
    comfyui-attn-runtime:latest
fi
