name: Docker Build and Push

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile/ubuntu24_cuda12.8_sageattention.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/comfyui-nvidia-docker:ubuntu24-cuda12.8-sageattention